1. What is a Python library? Why do we use Python libraries?

ans=python library is a collection of modules and packages that provide pre-written and reusable code to perform specific task  like 1. code reusability  2, productivity  3, standarlization 4, performance 5, community support  6, speicalized functionaliy


2. What is the difference between Numpy array and List?
ans= in numpy array all elements are different type  where list have different type of elements are available. 

2. numpy array is faster than list 
3.numpy array more memory efficient than list

find the shape size and dimmension of following array ?


In [4]:
import numpy as np
arr=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]



In [6]:
shape_arr=np.array(arr)
shape_arr.shape  #shape


(3, 4)

In [8]:
#dimenssion 
shape_arr.ndim

2

In [9]:
#size
shape_arr.size

12

4. Write python code to access the first row of the following array?



In [10]:
arr2=shape_arr
arr2[0,:]

array([1, 2, 3, 4])

5. How do you access the element at the third row and fourth column from the given numpy array?



In [12]:
arr2[2,3]

12

6. Write code to extract all odd-indexed elements from the given numpy array?



In [13]:
arr2[:, 1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

7. How can you generate a random 3x3 matrix with values between 0 and 1?


In [15]:
np.random.randint(0,1,size=(3,3))

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

8. Describe the difference between np.random.rand and np.random.randn?

np.random.rand is the uifrom distribution of {0,1} and  give the respected values and np.random.randn gives the value like normal distribution using and it is also called gausian distribution 

9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [18]:
original_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Increase the dimension by adding a new axis
new_dimension_array = original_array[:, :, np.newaxis]
print(new_dimension_array)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


10. How to transpose the following array in NumPy

In [20]:
transposed_array = np.transpose(original_array)
print(transposed_array)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consider the following matrix:

Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

In [22]:
#index wise multiplication
import numpy as np

# Given matrices
matrix_A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrix_B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Element-wise multiplication
result_matrix = matrix_A * matrix_B

print("Matrix A:")
print(matrix_A)

print("\nMatrix B:")
print(matrix_B)

print("\nElement-wise Multiplication (Index-wise):")
print(result_matrix)


Matrix A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix B:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Element-wise Multiplication (Index-wise):
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [23]:
#matrix multiplication

import numpy as np

# Given matrices
matrix_A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrix_B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# Matrix multiplication using numpy.dot
result_matrix = np.dot(matrix_A, matrix_B)

# Alternatively, you can use the @ operator
# result_matrix = matrix_A @ matrix_B

print("Matrix A:")
print(matrix_A)

print("\nMatrix B:")
print(matrix_B)

print("\nMatrix Multiplication:")
print(result_matrix)


Matrix A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix B:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Matrix Multiplication:
[[ 70  80  90]
 [158 184 210]
 [246 288 330]]


In [28]:
import numpy as np

# Given matrices
matrix_A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrix_B = np.array([[1, 2, 3,4], [ 5, 6,7,8], [9, 10, 11,12]])

# Matrix addition using numpy.add
result_matrix = np.add(matrix_A, matrix_B)

print("Matrix A:")
print(matrix_A)

print("\nMatrix B:")
print(matrix_B)

print("\nMatrix Addition:")
print(result_matrix)


Matrix A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix B:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix Addition:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [30]:
import numpy as np

# Given matrices
matrix_A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrix_B = np.array([[1, 2, 3,4], [ 5, 6,7,8], [9, 10, 11,12]])

# Matrix addition using numpy.add
result_matrix = np.subtract(matrix_A, matrix_B)

print("Matrix A:")
print(matrix_A)

print("\nMatrix B:")
print(matrix_B)

print("\nMatrix substraction:")
print(result_matrix)


Matrix A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix B:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix substraction:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [31]:
#divide matrix b from a 

import numpy as np

# Given matrices
matrix_A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrix_B = np.array([[1, 2, 3,4], [ 5, 6,7,8], [9, 10, 11,12]])

# Matrix addition using numpy.add
result_matrix = np.divide(matrix_A, matrix_B)

print("Matrix A:")
print(matrix_A)

print("\nMatrix B:")
print(matrix_B)

print("\nMatrix  divide:")
print(result_matrix)


Matrix A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix B:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix  divide:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


12. Which function in Numpy can be used to swap the byte order of an array?

In NumPy, the function used to swap the byte order (endianness) of an array is numpy.ndarray.byteswap. This function swaps the byte order of the array in place.

13. What is the significance of the np.linalg.inv function?

The np.linalg.inv function in NumPy is used to compute the multiplicative inverse of a matrix. Given a square matrix A, if there exists a matrix B such that A * B = B * A = I (where I is the identity matrix), then B is the inverse of A. In other words, the inverse of a matrix undoes the effect of the original matrix.

14. What does the np.reshape function do, and how is it used?

The np.reshape function in NumPy is used to give a new shape to an array without changing its data. It returns a new array with the specified shape. The elements of the original array are read in a certain order and placed into the new array.

15. What is broadcasting in Numpy?

NumPy broadcasting is a powerful feature that allows operations between arrays of different shapes and sizes. It automatically performs element-wise operations, even if the arrays are not of the same shape, by "broadcasting" the smaller array to match the shape of the larger one.